services:
  db:
    image: postgres:16
    container_name: gearup-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - gearup_network
    volumes:
      - gearup_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
        timeout: 20s
        retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5255:8080"
    environment:
      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
      Redis__ConnectionString: redis:6379
      Jwt__Issuer: ${Jwt__Issuer}
      Jwt__Audience: ${Jwt__Audience}
      Jwt__AccessToken_SecretKey: ${Jwt__AccessToken_SecretKey}
      Jwt__EmailVerificationToken_SecretKey: ${Jwt__EmailVerificationToken_SecretKey}
      BREVO_API_KEY: ${BREVO_API_KEY}
      FromEmail: ${FromEmail}
      ClientUrl: ${ClientUrl}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      CLOUDINARY_URL: ${CLOUDINARY_URL}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - db
      - redis
      - aspire-dashboard
    networks:
      - gearup_network
    restart: on-failure

  redis:
    image: redis:latest
    container_name: gearup-redis
    ports:
      - "6379:6379"
    networks:
      - gearup_network

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    container_name: aspire-dashboard
    restart: unless-stopped
    ports:
      - "18888:18888"   # UI
      - "4317:18889"    # OTLP gRPC (standard port)
      - "4318:18890"    # OTLP HTTP (standard port)
    networks:
      - gearup_network


volumes:
  gearup_data:

networks:
    gearup_network:




